<Project Sdk="Godot.NET.Sdk/4.6.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>littlegodotriver</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference
      Include="../../../../sanctuary/rzeka/core/Rzeka.Core.csproj"
      Condition="Exists('../../../../sanctuary/rzeka/core/Rzeka.Core.csproj')"
    />
    <ProjectReference
      Include="../../../../sanctuary/rzeka/dev/Rzeka.Dev.csproj"
      Condition="Exists('../../../../sanctuary/rzeka/dev/Rzeka.Dev.csproj')"
    />
    <PackageReference
      Include="EternalGarden.Rzeka"
      Version="1.1.0"
      Condition="!Exists('../../../../sanctuary/rzeka/core/Rzeka.Core.csproj')"
    />
    <PackageReference
      Include="EternalGarden.Rzeka.Dev"
      Version="1.1.0"
      Condition="!Exists('../../../../sanctuary/rzeka/dev/Rzeka.Dev.csproj')"
    />
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>
</Project>
